### ISSUE TITLE
ability to add custom repos

### ISSUE THREAD

**Issue by dnkmmr69420** [ivan-hc/AM-Application-Manager#108]
that would be a very useful feature so we aren't limited to one repository

**Comment by ivan-hc** [comment]
why not to merge that stuff here?

My goal here is to group together all the AppImage packages scattered around the web. AM would lose all meaning. There are other catalogs out there, the various "appimagehubs", which in reality are not real repositories. They do not provide updates or bug tracking and referral links to the main developer sites and repositories. My repository alone collects over 1800 AppImages. No known catalog has so many.

I fight to keep the AppImage format alive, which is all too ridiculed by the way it is handled by others.

In addition to this repository, there is an actual catalog created by me, see https://portable-linux-apps.github.io

I am the first to have invented a repository of AppImage packages (or scripts to install and find them, AUR PKGBUILD style), in the 20 years that this packaging format has existed.

Authorizing third-party repository access compared to this would be a huge step backwards!

It would mean continuing to divide what I am trying to unite. I don't know if I can explain myself.

Maybe in the future I will be able to consider diverting the repository towards something larger and more community-based, but as long as I work alone on all this and AM is still an unknown tool to most people, with around 250 stars on github, there's no question of it.

People are losing interest in AppImage, and the mere fact that my work here is still unknown is a serious damage to AppImage's reputation.

Finally, if you want to "install", or rather, "integrate" third-party packages without necessarily having to update them (as most tools do, from Appimagelauncher to Gearlever and Zap), there is the `--launcher` option, write the command `am --launcher` and drag the AppImage into the terminal, hit enter and the package is integrated into the menu with launcher and icon.

Third party repositories... bah! There are no repositories for AppImages. I'm the only one who invented one. And I'm not a developer, let's be clear. I am an unemployed ex-gastronomist looking for work and who now has a lot of time to waste, here on github just for fun. That's all.

**Comment by ivan-hc** [comment]
PS: as you can see... the issue you opened at https://github.com/ivan-hc/AM-Application-Manager/issues/107 is a consequence of the fact that too many distributions are breaking support for AppImages, causing problems, and the fact that you contacted me about that problem is a sign that the community that supports AppImages is not active, and people are leaving it, none care about this packaging format anymore!

Flatpak has it all, what do you want to expect from the GNOME team supported by Fedora, supported by Red Hadt, supported by IBM, supported by millions of dollars of investments?

We are very few assholes now fighting for this packaging format, also because no one knows us, nor does anyone want to take us into consideration.

**Comment by dnkmmr69420** [comment]
but what if someone wants to create a private repo for testing purposes?

**Comment by ivan-hc** [comment]
Then replace the environment variable `$APPREPO` with something else:
```
AMREPO="https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main"
```

**Comment by ivan-hc** [comment]
@dnkmmr69420 what if I allow the installation / test of local scripts?

**Comment by ivan-hc** [comment]
I hope this is enough https://github.com/ivan-hc/AM-Application-Manager/releases/tag/5.6

https://github.com/ivan-hc/AM-Application-Manager/assets/88724353/fa0e8627-6beb-47fc-a52f-0d32e392c7ce

**Comment by dnkmmr69420** [comment]
> PS: as you can see... the issue you opened at #107 is a consequence of the fact that too many distributions are breaking support for AppImages, causing problems, and the fact that you contacted me about that problem is a sign that the community that supports AppImages is not active, and people are leaving it, none care about this packaging format anymore!
> 
> Flatpak has it all, what do you want to expect from the GNOME team supported by Fedora, supported by Red Hadt, supported by IBM, supported by millions of dollars of investments?
> 
> We are very few assholes now fighting for this packaging format, also because no one knows us, nor does anyone want to take us into consideration.

It should be like flatpak. Your repo would be the main repo like flathub but people have the freedom to make their own

**Comment by ivan-hc** [comment]
@dnkmmr69420 even if I did, it would be useless. As I already told you, there are no alternative repositories.

However no one is stopping you from disabling the "-s" option for the CLI (just comment out the line where only "`_sync_amcli`" appears, i.e. like this "`#_sync_amcli`") and redirect the repository (variable "$AMREPO" ) towards something else.

But if you really think it is necessary to entice people to add more repositories, you could start spamming your social networks with my project trying to make it a little more popular... since almost all developers are abandoning AppImages. Maybe we can reverse the trend, don't you think? We would make people understand that there is an alternative.

PS: about...
> the issue you opened at https://github.com/ivan-hc/AM-Application-Manager/issues/107

you have to excuse me, I mistook you for another user who has a profile picture similar to yours and who contacts me often.

**Comment by ivan-hc** [comment]
@dnkmmr69420  This is how shoult look alike an option like the one you said:
```
  'newrepo')

	_no_sudo
	_online_check

	case $2 in
	'') echo -e "\n USAGE: $AMCLI $1 [URL]	# Set a new repository"
	    echo "        $AMCLI $1 off		# Disable the custom repository"
	    echo -e "        $AMCLI $1 on		# Enable the custom repository\n"; exit;;
	esac

	while [ -n "$1" ]; do
		case $2 in
		off|OFF)
			if test -f $AMPATH/new-repo.txt; then
				mv $AMPATH/new-repo.txt $AMPATH/new-repo.old
			else
				exit
			fi
			echo "Custom repository DISABLED!"
			exit;;
		on|ON)
			if test -f $AMPATH/new-repo.old; then
				mv $AMPATH/new-repo.old $AMPATH/new-repo.txt
			elif test -f $AMPATH/new-repo*; then
				echo "You have not a custom repository!"
			else
				exit
			fi
			echo "Custom repository ENABLED!"
			exit;;
		*)
			rm -R -f $AMPATH/new-repo.txt
			echo "$2" >> $AMPATH/new-repo.txt
			echo -e "\nYour custom repository is:\n\n $2\n\n This will replace the main one!\n"
			echo -e ' Use the command "'$AMCLI' newrepo off" to restore the default one!\n'
			echo -e ' Repeat this command with a new URL to replace the one you just set!\n'
			exit
			;;
		esac
	done

	shift
	;;
```
the new url must be saved in /opt/am/new-repo.txt (or elsewhere if you use AppMan) and at the begin of the script a test to select which value to set in AMREPO, depending if new-repo.txt is in place.

**Comment by ivan-hc** [comment]
### New release 5.6.2 is out!

https://github.com/ivan-hc/AM-Application-Manager/releases/tag/5.6.2
