### ISSUE TITLE
add more apps

### ISSUE THREAD

**Issue by Drsheppard01** [ivan-hc/AM-Application-Manager#14]
https://github.com/ArmCord/ArmCord/releases/download/v3.2.0/ArmCord-3.2.0.AppImage
https://github.com/ArmCord/ArmCord/releases/download/v3.2.0/ArmCord-3.2.0-arm64.AppImage
https://github.com/ArmCord/ArmCord/releases/download/v3.2.0/ArmCord-3.2.0-armv7l.AppImage

https://github.com/nanu-c/axolotl/releases/download/v1.6.0/Axolotl-x86_64.AppImage

https://github.com/LinwoodDev/Butterfly/releases/download/v2.0.0-alpha.4/linwood-butterfly-linux.AppImage

https://github.com/cemu-project/Cemu/releases/download/v2.0-39/Cemu-2.0-39-x86_64.AppImage

https://github.com/diasurgical/devilutionX/releases/download/1.4.1/devilutionx-linux-x86_64.appimage

https://github.com/SpartanJ/ecode/releases/download/ecode-0.4.8/ecode-linux-0.4.8-x86_64.AppImage
https://github.com/SpartanJ/ecode/releases/download/ecode-0.4.8/ecode-linux-0.4.8-aarch64.AppImage

https://github.com/elk-zone/elk-native/releases/download/elk-native-v0.4.0/Elk_0.4.0_linux_x86_64.AppImage

https://featherwallet.org/files/releases/linux-appimage/feather-2.4.5.AppImage
https://featherwallet.org/files/releases/linux-arm64-appimage/feather-2.4.5-arm64.AppImage
https://featherwallet.org/files/releases/linux-arm-appimage/feather-2.4.5-arm.AppImage
https://featherwallet.org/files/releases/linux-riscv64-appimage/feather-2.4.5-riscv64.AppImage

https://github.com/flareteam/flare-game/releases/download/v1.14/flare-linux64-v1.14.AppImage

https://github.com/flyinghead/flycast/releases/download/V2.1/flycast-x86_64.AppImage

https://github.com/gaphor/gaphor/releases/download/2.18.1/Gaphor-2.18.1-x86_64.AppImage

https://github.com/gdm-settings/gdm-settings/releases/download/v3.1/Login_Manager_Settings.AppImage

https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/releases/download/v2.9.5/Icalingua++-2.9.5.AppImage
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/releases/download/v2.9.13/Icalingua++-2.9.13-arm64.AppImage
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/releases/download/v2.9.13/Icalingua++-2.9.13-armv7l.AppImage

https://github.com/Kong/insomnia/releases/download/core%402023.2.2/Insomnia.Core-2023.2.2.AppImage

https://github.com/TheGoddessInari/hamsket/releases/download/nightly/Hamsket-0.6.5.AppImage

https://github.com/helix-editor/helix/releases/download/23.05/helix-23.05-x86_64.AppImage
https://github.com/helix-editor/helix/releases/download/23.05/helix-23.05-aarch64.AppImage

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.7.1/Heroic-2.7.1.AppImage

https://github.com/kopia/kopia/releases/download/v0.13.0/KopiaUI-0.13.0.AppImage
https://github.com/kopia/kopia/releases/download/v0.13.0/KopiaUI-0.13.0-arm64.AppImage
https://github.com/kopia/kopia/releases/download/v0.13.0/KopiaUI-0.13.0-armv7l.AppImage

https://github.com/lbryio/lbry-desktop/releases/download/v0.53.9/LBRY_0.53.9.AppImage

https://api.k8slens.dev/binaries/Lens-2023.4.60821-latest.x86_64.AppImage

https://github.com/localsend/localsend/releases/download/v1.9.1/LocalSend-1.9.1.AppImage

https://lunatask.app/download/Lunatask-1.6.6.AppImage

https://github.com/ThaUnknown/miru/releases/download/v3.10.6/linux-Miru-3.10.6.AppImage

https://github.com/naev/naev/releases/download/v0.10.5/naev-0.10.5-linux-x86-64.AppImage

https://github.com/neovim/neovim/releases/download/v0.9.0/nvim.appimage

https://web.onekey-asset.com/app-monorepo/4.6.0/OneKey-Wallet-4.6.0-linux-x86_64.AppImage

https://github.com/Bwc9876/ow-mod-man/releases/download/gui_v0.6.1/outer-wilds-mod-manager_0.6.1_amd64.AppImage

https://download.owncloud.com/desktop/ownCloud/stable/4.0.0.10896/linux-appimage/ownCloud-4.0.0.10896-x86_64.AppImage

https://github.com/PCSX2/pcsx2/releases/download/v1.7.4529/pcsx2-v1.7.4529-linux-AppImage-64bit-Qt.AppImage

https://github.com/pencil2d/pencil/releases/download/v0.6.6/pencil2d-linux-amd64-0.6.6.AppImage
https://github.com/pencil2d/pencil/releases/download/v0.6.6/pencil2d-linux-i386-0.6.6.AppImage

**Comment by ivan-hc** [comment]
Hi, and thank you!

I have just added the 22 apps for x86_64 available on github (not those for ARM because I don't use that harware, so banally I don't know much about the apps that can work on it).

Now I have to add these five:

https://api.k8slens.dev/binaries/Lens-2023.4.60821-latest.x86_64.AppImage
https://download.owncloud.com/desktop/ownCloud/stable/4.0.0.10896/linux-appimage/ownCloud-4.0.0.10896-x86_64.AppImage
https://featherwallet.org/files/releases/linux-appimage/feather-2.4.5.AppImage
https://lunatask.app/download/Lunatask-1.6.6.AppImage
https://web.onekey-asset.com/app-monorepo/4.6.0/OneKey-Wallet-4.6.0-linux-x86_64.AppImage

To check a way to download the latest version of an app on other sites sometime is difficult.

**Comment by Drsheppard01** [comment]
here are a few more applications I know of. I would also like to help clear the list of irrelevant applications (abandoned, unaccompanied). See: https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/issues/1 

https://purei.org/downloads/play/stable/0.60/Play!-9a55785a-x86_64.AppImage

https://github.com/Barre/privaxy/releases/download/v0.5.2/privaxy_0.5.2_amd64.AppImage

https://github.com/jlambert360/FPM-AppImage/releases/download/v2.3.2/Faster_Project_Plus-x86-64.AppImage

https://github.com/pulsar-edit/pulsar/releases/download/v1.105.0/Linux.Pulsar-1.105.0.AppImage
https://github.com/pulsar-edit/pulsar/releases/download/v1.105.0/ARM.Linux.Pulsar-1.105.0-arm64.AppImage

https://sourceforge.net/projects/qtractor/files/latest/download

https://github.com/Dummerle/Rare/releases/download/1.10.1/Rare-1.10.1.AppImage

https://github.com/adil192/saber/releases/download/v0.12.8/Saber-0.12.8-x86_64.AppImage

https://sourceforge.net/projects/scribus/files/scribus-devel/1.5.8/scribus-1.5.8-linux-x86_64.AppImage/download

https://github.com/KRTirtho/spotube/releases/download/v2.7.1/Spotube-linux-x86_64.AppImage

https://github.com/0neGal/viper/releases/download/v1.7.3/Viper-1.7.3.AppImage

https://github.com/vup-app/vup/releases/download/v0.12.0/Vup-0.12.0-BETA-Linux.AppImage

https://github.com/xemu-project/xemu/releases/download/v0.7.90/xemu-v0.7.90-x86_64.AppImage

https://github.com/yuzu-emu/yuzu-mainline/releases/download/mainline-0-1445/yuzu-mainline-20230525-1c694c2bb.AppImage

**Comment by ivan-hc** [comment]
Right now I'm working on a new release that includes a new option 8 for the command `am -t` that will help any experience user in downloading the last version of an AppImage from everywhere... but again, Github has a description in almost all the repositories (and this helps a lot not just because we have to compile the lists, the option `-q` uses keywords to find what you're looking for... but also to create new pages on https://portable-linux-apps.github.io , being these downloaded with the option `-a`) , the option already do all we need for the AppImage packages... but for other sites I need a description, I don't know what these apps willdo.

It would be more helpful if the next time you share these links this way:

- Github
- - https://github.com/Name1/Repo1
- - https://github.com/Name1/Repo2
- - https://github.com/Name2/Repo1

...

- Other sites:
- - https://www.something.com # This program do this
- - https://another.amazing.program.us # This other program can do this other thing

...

In this way I'll be faster when I upload the apps. If you provide all these direct links I need to copy them all to a file, then using `cat` and `grep` to separate the apps hosted on github from those coming from another site, remove the architectures and finally copy/paste only what I need to complete my actions. And believe me, this take a lot of time, The five URLs of my previous message are still there, I've not uploaded nothing for now because I must implement new functions to improve my workflow with these apps (and here are 5 a.m., in Italy).

So, thank you for all these links and all your interest in this project. You don't need to give me all these direct links, but just a part of them... and maybe this database will beat Flathub in terms of apps included ;)

**Comment by Drsheppard01** [comment]
Well, is it necessary to correct all the sites above now?

**Comment by ivan-hc** [comment]
Not for now, save your energy for next time ;)

**Comment by Drsheppard01** [comment]
>  and maybe this database will beat Flathub in terms of apps included

As for flatpak, we have a kind of vendor-lock, since new gnome applications are built with the gnome-builder and packed into flatpak, it would be great if AppImage had its own IDE (or a plugin for it) that included a build system. I also posted a couple of ideas about what AppImage needs https://social.linux.pizza/@drsheppard/109779906807566912

**Comment by ivan-hc** [comment]
Just finished to adjust old installation scripts and removed those no more available or no more downloadable, if you see the `am -l` command will list 1524 apps now... until two days ago (when I uploaded the first github links you have shared) they were more than 1540. During this work I've also discovered new methods to convert my old scripts, but those more difficult were those available on dedicated sites, there is not one method to get the latest available version.

Ill start uploading at least the links for github, soon, but I come from 8 hours of work on this repository, I have to sleep first.

**Comment by ivan-hc** [comment]
Mission complete, all the apps are uploaded and tested successfully.

**Comment by Myzel394** [comment]
I can't find feather wallet - has it been removed?

**Comment by ivan-hc** [comment]
@Myzel394 I accidentally created it with the name "featerwallet", I reuploaded it as "feather-wallet". I forgot an H (the trouble with not being native English speakers).

**Comment by Myzel394** [comment]
No worries, thanks for the quick fix!

I'm a bit confused though. I tried to list all entries and filter them out using grep:

```bash
am -l | grep "Monero"
```

but was unable to find "featerwallet" but now I can find "feather-wallet" - do you know why this is the case? The description for "featerwallet" contains "Monero" in it:

```
A free, open-source Monero wallet.
```

so I guess it should find it

**Comment by ivan-hc** [comment]
@Myzel394 I don't know this app, I don't use it and I don't know what it does and what "Monero" means... but I've seen your previous comment, so I have done a search (on Google) and uploaded a new script for it and edited the list thanks to your message... after that I noticed that (time ago) I was wrong while creating the installation script and wrote the name of the app in the wrong way (so I have removed "featerwallet" being it a wrong duplicate). Now is fixed, I've done the commit https://github.com/ivan-hc/AM-Application-Manager/commit/8e9031cd11940e747e663d136f2929576df8cffc after I have seen your message, also I have uploaded the new page on https://portable-linux-apps.github.io
