### ISSUE TITLE
i have some info for you

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/AM-Application-Manager#44]
is china dev people , they build same 3a GAME.
https://www.linuxgame.cn/

like this
https://www.linuxgame.cn/shadow-of-the-tomb-raider
https://www.linuxgame.cn/%e6%b6%88%e9%80%9d%e7%9a%84%e5%85%89%e8%8a%92-dying-light

not use steam, it run every 

help you too build app  for some give idea

:)

**Comment by ivan-hc** [comment]
This is interesting, but I cannot find a download link to the AppImages, I only can see some instructions for SPT or DNF. Also they seems to be proprietary games.

**Comment by newyorkthink** [comment]
https://de.linuxgame.cn/%E5%8F%A4%E5%A2%93%E4%B8%BD%E5%BD%B1%E6%9A%97%E5%BD%B1/Shadow_of_the_Tomb_Raider_1.0_amd64.appimage

**Comment by newyorkthink** [comment]
![image](https://github.com/ivan-hc/AM-Application-Manager/assets/87791643/42fe0f42-24b1-4a07-bd0c-9cd558a47a0e)
![image](https://github.com/ivan-hc/AM-Application-Manager/assets/87791643/d5f1b9e2-c0f7-4ffa-a803-8efa1d8b78fa)

**Comment by newyorkthink** [comment]
> This is interesting, but I cannot find a download link to the AppImages, I only can see some instructions for SPT or DNF. Also they seems to be proprietary games.

https://www.linuxgame.cn/download/%E5%8F%A4%E5%A2%93%E4%B8%BD%E5%BD%B1%E5%B4%9B%E8%B5%B7/riseofthetombraider_1.0_amd64.appimage

https://de.linuxgame.cn/%E5%8F%A4%E5%A2%93%E4%B8%BD%E5%BD%B1%E6%9A%97%E5%BD%B1/Shadow_of_the_Tomb_Raider_1.0_amd64.appimage

**Comment by newyorkthink** [comment]
this is all appimage , you can see it
||||
https://de.linuxgame.cn/

**Comment by ivan-hc** [comment]
it would be good if at least the 90% of them are freewase or fre and open source... but on the contrary the great part of them in proprietary and "should" have a cost... and here are all downloadable for free. Here in Italy we call this "piracy".

Thank you for this info, but I'm not interested in distributing games illegally. If I bundle a web browser (like Chrome or Vivaldi) I try to made it work well at least, they are proprietary apps but are available for free, I would only be responsible for their malfunction.

But games... many of them involve hard work behind them and consequently there are also costs to bear, and they are very high. That's why Steam centralized the gaming service on it, to prevent illegal sharing of these games. I also have original games that I packaged as AppImages, but for personal use! I can't distribute them, it's illegal. I don't know how the law works in China on these licenses, but it's illegal here.

Sorry, but I won't upload any apps from there (including 0ad and SuperTuxKart, which are at least available on github and AM, and are open source).

Cheers
