### ISSUE TITLE
AM-Application-Manager  appimage files location ?

### ISSUE THREAD

**Issue by andrew-ysk** [ivan-hc/AM-Application-Manager#46]
Since after installation of  AM-Application-Manager, it managed to detect several  appimage program that not installed by AM-Application-manage on my system. 
It would be good if there is a function to show the location of each detected appimage programs  ?

**Comment by andrew-ysk** [comment]
i have for example several jitsi-meet installed on my system .. maybe i have forgotten that i have installed it before. 
1 is from flatpak, 1 is from appimage, the other 2 i have got no idea where it is from..  anyway to differentiate them apart so that i can manage them or delete them.

**Comment by ivan-hc** [comment]
> Since after installation of AM-Application-Manager, it managed to detect several appimage program that not installed by AM-Application-manage on my system

this is a bug like the one of the video of DT, happened because him was using an old version of AM (of one year ago).

Can you provide a screenshot of the output? Can you give me more details about this issue? Is your client updated?

**Comment by andrew-ysk** [comment]
Is there way for AM to have a log of each installed/ removed appimage log file ?  

$ am -f
YOU HAVE INSTALLED 3 STANDALONE PROGRAMS MANAGED BY 'AM':
 ◆ am - 240KiB of disk space used
 ◆ jitsi-meet - 95MiB of disk space used
 ◆ stacer - 30MiB of disk space used

I know stacer  were installed using AM, and AM was installed from github. 
However, i am not sure i have installed jitsi-meet.  **very forgetful**

I have (from your github) learnt that AM always put appimage file in /opt and link to /usr/local/bin. 
usually appimage file (for good practice) is appended with *.appimage at the back for easy of knowing.  However AM does not do that.. :-)  
Do you think appimage extension will be better , less confusion ?

**Comment by ivan-hc** [comment]
jitsi-meet seems to be managed by AM, the directory structure should be this:

    /opt/jitsi-meet/AM-updater
    /opt/jitsi-meet/jitsi-meet
    /opt/jitsi-meet/icons/jitsi-meet
    /opt/jitsi-meet/remove
    /opt/jitsi-meet/version

> usually appimage file (for good practice) is appended with *.appimage at the back for easy of knowing

a good practice is a question of points of view. I decided to install the apps into a specific path, according with the Linux Standard Base (LSB) and without creating an "Applications" directory in the main root  (for privileged users).

AppImage is a portable format, but using AM you decide to put it into a specific path, like any other program.

Another thing, I developed AM not for those users decided to have both versions of a program on their system, but for those who want a program because the version from repositories is too old, not available or takes too much disk space (Appimage is a compressed file system).

If you want to download the Appimages by mantaining the extension you can use `am -a $PROGRAM` and go to the developer's site, you can download the package from there (without managing anything via AM, in that case you need AppimageLauncher or other stuff I decided to reject by developing AM and AppMan).
