### ISSUE TITLE
any way to downgrade apps

### ISSUE THREAD

**Issue by Ranko-Saotome** [ivan-hc/AM-Application-Manager#61]
Any way to downgrade apps Because the current version of Joplin I downloaded when I recently updated is currently broke on my system?

**Comment by Ranko-Saotome** [comment]
last working version is joplin-2.12.5

**Comment by ivan-hc** [comment]
you should download it manually, first of all you should disable the "AM-updater" script:
```
am lock joplin
```
then go to the repository of joplin, you can find the link with the command `am -a joplin`

once you have downloaded the version you need, rename it to "**joplin**" and replace **/opt/joplin/joplin** with the new one (in order to use the command `joplin` from the terminal) and made it executable (command `chmod a+x /opt/joplin/joplin`)

**Comment by ivan-hc** [comment]
PS: for the next time, do
```
am -b joplin
```
this command will create a backup of the version you have installed, so if something goes wrong, just run the command...
```
am -o joplin
```
to overwrite the new version with the previous one that worked for you.
