### ISSUE TITLE
Add OpenLens

### ISSUE THREAD

**Issue by pinarruiz** [ivan-hc/AM-Application-Manager#68]
Add the appimages hosted on [OpenLens](https://github.com/MuhammedKalkan/OpenLens).

**Comment by ivan-hc** [comment]
Anyway I added openlens's appimage package too, thanks https://github.com/ivan-hc/AM-Application-Manager/commit/ada65fd04e71f3aac44afac4d15cf6de1a9f2404

**Comment by ivan-hc** [comment]
@pinarruiz I can't find a source for these appimages, nor I can see a list of them, but I'm pretty sure that it uses something like appimagehub.com or something. Maybe I'm wrong and they are using their own server to store the apps, like apprepo.de do.

In both cases they are sources I can't trust much on. Also on github there have many appimages without instructions or source code that we can read to understand how the appimage is built, I prefer to stay away from them.

Also apprepo.de has workflows and scripts that we can read, but by reading the code it uses an external tool (named "apprepo.Appimage" or something) that I don't know what exactly does.

It's true that my "AM" has the sole purpose of distributing packages and that it's not my responsibility if those not produced by me do not work (I have built about forty, including GIMP and VLC), but I still want to limit the damage as much as possible. 

I myself try to install only original Appimage packages from the manufacturer's site or repository usin "AM" (especially mainstream apps, like kdenlive) or I build them myself, and if I have to test new ones as a precaution I always create a ".home" folder using the option -H of "AM". Unfortunately this command doesn't always work, due to how the software was designed (and coincidentally, OpenLens itself insists on creating a ".k8slens" folder in my main $HOME, not the dedicated one created with the command `am -H openlens`), and this is annoying, at least for me. But as long as app works and is rated this high (I see it is rated 3k stars, lucky him) it's fine to keep it for everybody.

Thanks for this report! :)
