### ISSUE TITLE
Issue with: cat: /opt/am/list: No such file or directory

### ISSUE THREAD

**Issue by danrobi11** [ivan-hc/AM-Application-Manager#7]
Everytime im opening any of my terminals they output this: `cat: /opt/am/list: No such file or directory`

I guess that's from the [install script L28](https://github.com/ivan-hc/AM-Application-Manager/blob/main/INSTALL#L28)?

Its true, there's no such file. Since everything is working fine, I assume that's no longer needed?

**Comment by danrobi11** [comment]
Nvm. That `$(cat /opt/am/list)" am'` is not present in the AppMan-2.2 install script.
Now the path on my end is: `/opt/appman/list`

So I still got a symlink or something from my previous `AM` install attemp?

I cant find what/where I need to delete in order to fix this.

**Comment by ivan-hc** [comment]
yes, the lates versions of AM have bash completion by default starting from the first installation and it can be removed with the command `sudo am --disable-completion` or by uninstalling am directly (command `sudo am -r am`) because the /etc/bash_completion.d/am-completion.sh file is listed in the /opt/am/remove script. Maybe you had an old version of am and the completion was not removed when you uninstalled am. Run `sudo rm -R /etc/bash_completion.d/am-completion.sh` to remove the script.
However, if you still have "am" and you want to keep "am", just give a list to "am", so run "`am -l`".

**Comment by danrobi11** [comment]
> sudo rm -R /etc/bash_completion.d/am-completion.sh

Perfect that fixed the issue. AppMAn still working fine :) Thanks again for the support :+1:  Closing

**Comment by ivan-hc** [comment]
@danrobi11 I have solved the issue in both AppMan and AM, you're free to enable the bash completion again.

**Comment by danrobi11** [comment]
@ivan-hc Awseome! Very nice that `-s` option :+1: 

Im a bit confuse tho. Should I run `AM` or `AppMan`?

**Comment by ivan-hc** [comment]
All depends on on your needings:

- if you want your applications to be accessible to other users using other accounts (ie they must be integrated with the system, such as the package manager) and you want to dedicate your home folder only to your data, choose "AM ";
- if you want to install applications in your home folder (so without using root privileges to install/remove them), choose "AppMan".

**Comment by danrobi11** [comment]
@ivan-hc Ok AppMan it will be. Thanks!
