### ISSUE TITLE
video from dt to readme?

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AM-Application-Manager#70]
[youtube](https://www.youtube.com/watch?v=7SfDlR3vU3I)

**Comment by ivan-hc** [comment]
Thanks, but no... the video wasn't well prepared, it uses an old and buggy 3.x version, while the version from back then, a year newer. See when it performs `-u`, "AM" is updated at minute 7:19 from 3.0.6 to 4.3.1-1, and too many things were changed in that version, including the use of `less` using `-l`, as suggested previously in the video. So the newer version was even better, not exactly a good advertisement in short (just read comments).

I certainly owe a lot of popularity of this project to DT, but the video could have been prepared better, there are too many defects that make it in the eyes of the public yet another failed attempt to provide a tool for managing AppImages, while my goal was to to make it a permanent solution.

I don't want to be arrogant and presumptuous with this consideration of mine, personally I don't even consider myself a developer, I write bash scripts as a hobby (and normally I work in supermarkets, so this is not a good background for a professional developer)... but if a project is revised it is better that it is done on the current version, not on the one-year old one and only because you have in a hurry to upload a video after my insistence on his Reddit page (as mentioned at the beginning, it almost seems like I want to settle for the rush of get out away a spammer out of his balls).

That's all.
