### ISSUE TITLE
use `/usr/local/share` instead of `/usr/share`

### ISSUE THREAD

**Issue by dnkmmr69420** [ivan-hc/AM-Application-Manager#71]
I am on silverblue and you can't modify `/usr/share`

**Comment by ivan-hc** [comment]
is this because the distro is immutable? if so try the command `am --user` and use the alias by default (in your .bashrc file), "AM" will act exactly like [Appman](https://github.com/ivan-hc/AppMan), in your $HOME directory.

I see that this is a problem with the launchers (the .desktop files), I have choosen that path because with "AM" I should also create a /usr/local/share/applications directory, and I'd like to keep the system's directories as much clean as possible.

**Comment by dnkmmr69420** [comment]
> is this because the distro is immutable? if so try the command `am --user` and use the alias by default (in your .bashrc file), "AM" will act exactly like [Appman](https://github.com/ivan-hc/AppMan), in your $HOME directory.
> 
> I see that this is a problem with the launchers (the .desktop files), I have choosen that path because with "AM" I should also create a /usr/local/share/applications directory, and I'd like to keep the system's directories as much clean as possible.

there are also some things that I would like to install system wide as well

**Comment by ivan-hc** [comment]
We will keep talk in the other issue https://github.com/ivan-hc/AM-Application-Manager/issues/86

**Comment by ivan-hc** [comment]
I've solved with this commit https://github.com/ivan-hc/AM-Application-Manager/commit/f758f5e1848e5d9ddaa0b307fe40cc40d0046c6e update to AM 5.1
