### ISSUE TITLE
Blender not latest stable version installed

### ISSUE THREAD

**Issue by Martin15135215** [ivan-hc/AM-Application-Manager#83]
The latest stable version is 3.6.4

**Comment by Martin15135215** [comment]
https://www.blender.org/download/
https://download.blender.org/release/

It's a bit difficult, since there is no official API.

**Comment by ivan-hc** [comment]
I was sure I created the scripts to point to the latest version, but I remember that the page was a little different before (about two years ago), so the position of the packages must have been reversed (the latest versions are now at the top , first they had to be at the bottom, otherwise I can't explain this).

This confirms https://github.com/ivan-hc/AM-Application-Manager#wrong-download-link
